replicaCount: 2

image:
  repository: russianbear107/user_crud
  tag: "1.0"

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    type: NodePort
    port: "5432"
  postgresqlExtendedConf:
    {'shared_preload_libraries':'pg_stat_statements'}
  
metrics:
  serviceMonitor:
    enabled: true
  
ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/otusapp"]
      
test:
  image: russianbear107/user_crud_test
  imageTag: "1.0"
