apiVersion: batch/v1
kind: Job
metadata:
  name: crud-initdb
spec:
  template:
    metadata:
      name: crud-initdb
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        env:
          - name: DATABASE_URI
            value: "postgresql://myuser:passwd@postgres/myapp"
        image: postgres:latest
        command:
          - sh
          - "-c"
          - |
            psql $DATABASE_URI <<'EOF'
              create table client (id serial primary key, username varchar(256) not null, firstName varchar, lastName varchar, email varchar, phone varchar);
              create unique index uk_username on client(username);
            EOF
      initContainers:
      - name: check-db-ready
        image: postgres:latest
        env:
          - name: POSTGRES_HOST
            value: postgres
          - name: POSTGRES_PORT
            value: "5432"
        command:
          - sh
          - "-c"
          - |
            until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT; 
            do echo waiting for database; sleep 2; done;            
  backoffLimit: 0
